// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivvpoqsghddkngywoesg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dnBvcXNnaGRka25neXdvZXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTQzMTIsImV4cCI6MjA2NDc3MDMxMn0.mjLR6EkRbVHek2eoDrRbhQG_CFltRdAqLXNuobx1GOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);